name: Pro Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Code Download
        uses: actions/checkout@v3

      - name: ⚙️ Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: "24" # Node ka naya version warning hatane ke liye

      - name: 📦 Packages Install
        run: npm install

      - name: 🔨 Website Build
        run: npm run build

      - name: 🚀 SSH se Pakka Upload
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "out/"
          target: "/home/u483648284/domains/aurabusinesssolution.com/public_html/pk"
          strip_components: 1
